apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gruesome-data
  namespace: gruesome
spec:
  accessModes: ["ReadWriteOnce"] # SQLite → single writer → single replica
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
