apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-data
  namespace: jupyter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi
